
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - sudo npm install -g typescript
      - sudo rm -rf node_modules
      - sudo rm -f package-lock.json
      - sudo npm cache clean --force
      - sudo npm install
  build:
    commands:
      - tsc

artifacts:
  files:
    - package.json
    - package-lock.json
    - 'build/**/*'
    - '.platform/**/*' # AWS Elastic Beanstalk configuration files
    - '.ebextensions/**/*' # AWS Elastic Beanstalk configuration files
  discard-paths: no