
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g typescript
      # - rm -rf node_modules
      # - rm -f package-lock.json
      # - npm cache clean --force
      - npm install
  build:
    commands:
      - tsc

artifacts:
  files:
    - package.json
    - package-lock.json
    - 'build/**/*'
    - '.platform/**/*' # AWS Elastic Beanstalk configuration files
    - '.ebextensions/**/*' # AWS Elastic Beanstalk configuration files
  discard-paths: no